### ISSUE TITLE
sir i am unable to use the tool sir

### ISSUE THREAD

**Issue by anich04** [TeamDefronix/Cyberonix#52]
![Screenshot 2024-05-31 082207](https://github.com/TeamDefronix/Cyberonix/assets/139942695/d1ba943c-575c-4173-a917-c885ce2a32d4)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by THECH13F** [comment]
please run ```python setup.py``` first or manually write ```pip install selenium```
